apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yhty2n6aw-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:48fbfacd0d5da3a8ce6355c7dfc67a85b88464bc@sha256:c56d3e30b740235322000ac3296702f2d67fb4ab78c77325e91ac7f77e2aa96a
          name: container-image
