apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yhty2n6aw-nodejs
  janus-idp.io/tekton: yhty2n6aw-nodejs
  backstage.io/kubernetes-id: yhty2n6aw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yhty2n6aw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
