apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yhty2n6aw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yhty2n6aw-nodejs 
  name: yhty2n6aw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yhty2n6aw-nodejs 
